apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ai-llm-reference-app.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "ai-llm-reference-app.name" . }}
