apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-llm-reference-app.fullname" . }}
spec:
  selector:
    app: {{ include "ai-llm-reference-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
